apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-pipeline-deployment-feature
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-devops-app2
  template:
    metadata:
      labels:
        app: hello-devops-app2
    spec:
      nodeSelector:
        branch: app2
      containers:
      - name: hellodevopsapp2
        image: joemuldowney/hellodevopsapp2
        ports:
        - containerPort: 5000