apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-pipeline-deployment
  namespace: devops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-devops
  template:
    metadata:
      labels:
        app: hello-devops
    spec:
      containers:
      - name: hellodevops
        image: joemuldowney/hellodevops:latest
        ports:
        - containerPort: 5000
