---
apiVersion: v1
kind: Service
metadata:
  name: devops-pipeline-service
  namespace: devops
spec:
  type: NodePort
  selector:
    app: hello-devops
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30007