apiVersion: v1
kind: Service
metadata:
  name: devops-pipeline-service-feature
  namespace: devops
spec:
  type: NodePort
  selector:
    app: hello-devops-feature
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30008